import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Link from "next/link";
import { Toaster } from "@/components/ui/sonner";
import {
  Facebook,
  Twitter,
  Linkedin,
  Instagram,
  Mail,
  Phone,
  MapPin,
} from "lucide-react";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Nexto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ClerkProvider
          appearance={{
            baseTheme: dark,
          }}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="min-h-screen">{children}</main>
            <Toaster />
            <footer className="bg-background border-t border-muted mt-24">
              <div className="container mx-auto px-4 md:px-6 py-12 grid grid-cols-1 md:grid-cols-4 gap-8">
                {/* Company Info */}
                <div className="space-y-4">
                  <h3 className="text-xl font-bold">Nexto</h3>
                  <p className="text-muted-foreground text-sm">
                    AI-powered platform helping professionals grow their careers
                    with smart interview prep and personalized guidance.
                  </p>
                  <div className="flex space-x-4">
                    <a href="#" aria-label="Facebook">
                      <Facebook className="w-5 h-5 text-muted-foreground hover:text-primary" />
                    </a>
                    <a href="#" aria-label="Twitter">
                      <Twitter className="w-5 h-5 text-muted-foreground hover:text-primary" />
                    </a>
                    <a href="#" aria-label="LinkedIn">
                      <Linkedin className="w-5 h-5 text-muted-foreground hover:text-primary" />
                    </a>
                    <a href="#" aria-label="Instagram">
                      <Instagram className="w-5 h-5 text-muted-foreground hover:text-primary" />
                    </a>
                  </div>
                </div>

                {/* Quick Links */}
                <div className="space-y-4">
                  <h4 className="text-lg font-semibold">Quick Links</h4>
                  <ul className="space-y-2 text-sm text-muted-foreground">
                    <li>
                      <Link href="/dashboard" className="hover:text-primary">
                        Dashboard
                      </Link>
                    </li>
                    <li>
                      <Link href="/about" className="hover:text-primary">
                        About Us
                      </Link>
                    </li>
                    <li>
                      <Link href="/features" className="hover:text-primary">
                        Features
                      </Link>
                    </li>
                    <li>
                      <Link href="/contact" className="hover:text-primary">
                        Contact
                      </Link>
                    </li>
                  </ul>
                </div>

                {/* Resources */}
                <div className="space-y-4">
                  <h4 className="text-lg font-semibold">Resources</h4>
                  <ul className="space-y-2 text-sm text-muted-foreground">
                    <li>
                      <Link href="/blog" className="hover:text-primary">
                        Blog
                      </Link>
                    </li>
                    <li>
                      <Link href="/faq" className="hover:text-primary">
                        FAQ
                      </Link>
                    </li>
                    <li>
                      <Link href="/privacy" className="hover:text-primary">
                        Privacy Policy
                      </Link>
                    </li>
                    <li>
                      <Link href="/terms" className="hover:text-primary">
                        Terms of Service
                      </Link>
                    </li>
                  </ul>
                </div>

                {/* Contact Info */}
                <div className="space-y-4">
                  <h4 className="text-lg font-semibold">Contact Us</h4>
                  <div className="flex items-center space-x-2 text-sm text-muted-foreground">
                    <MapPin className="w-4 h-4" />
                    <span>123 Career St, Mumbai, India</span>
                  </div>
                  <div className="flex items-center space-x-2 text-sm text-muted-foreground">
                    <Phone className="w-4 h-4" />
                    <span>+91 9876543210</span>
                  </div>
                  <div className="flex items-center space-x-2 text-sm text-muted-foreground">
                    <Mail className="w-4 h-4" />
                    <span>support@nexto.com</span>
                  </div>
                </div>
              </div>

              <div className="border-t border-muted py-4 text-center text-sm text-muted-foreground">
                &copy; {new Date().getFullYear()} Nexto. Made by Muneeb.
                All rights reserved.
              </div>
            </footer>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
